apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config
  namespace: kube-system
data:
  policy.topology-aware: |+
    PinCPU: true
    PinMemory: true
    PreferIsolatedCPUs: true
    PreferSharedCPUs: false
  policy.static: |
    RelaxedIsolation: true
    Rdt: auto
  policy.stp: |+
    # This is an example configuration file for the builtin cmk policy
    # The imaginary example system here consists of 4 sockets, 4 cores (8
    # multithreaded CPUs)
    pools:
      exclusive:
        # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
        cpuLists:
        - Cpuset: 8,9
          Socket: 1
        - Cpuset: 10,11
          Socket: 1
        - Cpuset: 16,17
          Socket: 2
        - Cpuset: 18,19
          Socket: 2
        - Cpuset: 24,25
          Socket: 3
        - Cpuset: 26,27
          Socket: 3
        exclusive: true
      shared:
        # 2 cores in shared pool, all on socket 1
        cpuLists:
        - Cpuset: 12,13,14,15
          Socket: 1
        exclusive: false
      infra:
        # Rest of cores designated to infra pool
        cpuLists:
        - Cpuset: 0,1,2,3,4,5,6,7
          Socket: 0
        - Cpuset: 20,21,22,23
          Socket: 2
        - Cpuset: 28,29,30,31
          Socket: 3
        exclusive: false
  rdt: |+
    # Common options
    options:
      l3:
        optional: true
      mb:
        optional: true
    # This example config specifies three RDT classes (or resctrl groups) with L3
    # CAT configured
    resctrlGroups:
      Guaranteed:
        l3schema:
          all: "100%"
    # Specify CacheId (typically correspons CPU socket) specific setting
    #      1: "80%"
    # MBA (Memory Bandwidth Allocation)
    #    mbschema:
    #      all: 100
    #      1-3: 80
      Burstable:
        l3schema:
          all: "66%"
    # MBA (Memory Bandwidth Allocation)
    #    mbschema:
    #      all: 66
      BestEffort:
        l3schema:
          all: "33%"
    # MBA (Memory Bandwidth Allocation)
    #    mbschema:
    #      all: 33
