#
# This example creates 3 ConfigMaps:
#  - cri-resmgr-config.default: the default configuration
#  - cri-resmgr-config.group.foo: the configuration for nodes in group foo
#  - cri-resmgr-config.node.cl0-slave1: the configuration for node cl0-slave1
#
# You can assign nodes to group foo using the command
#   kubectl label --overwrite node $NODE_NAME cri-resource-manager.intel.com/group=foo
#
# You can remove nodes from group foo using the command
#   kubectl label node $NODE_NAME cri-resource-manager.intel.com/group-
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    topology-aware:
      PinCPU: true
      PinMemory: true
      PreferIsolatedCPUs: true
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # This is an example configuration for static-pools policy.
      # The imaginary example system here consists of 4 sockets, 4 cores, 2 threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    config:
      # Common options
      options:
        l3:
          optional: true
        mb:
          optional: true
      # This example config specifies three RDT classes (or resctrl groups) with L3
      # CAT configured
      resctrlGroups:
        Guaranteed:
          l3schema:
            all: "100%"
      # Specify CacheId (typically correspons CPU socket) specific setting
      #      1: "80%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 100
      #      1-3: 80
        Burstable:
          l3schema:
            all: "66%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 66
        BestEffort:
          l3schema:
            all: "33%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 33
  dump: |+
    Config: full:.*,debug
    File: /tmp/cri-full-debug.dump
  logger: |+
    Debug: resource-manager,cache,policy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.group.foo
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    topology-aware:
      PinCPU: true
      PinMemory: false
      PreferIsolatedCPUs: false
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # This is an example configuration for static-pools policy.
      # The imaginary example system here consists of 4 sockets, 4 cores, 2 threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    config:
      # Common options
      options:
        l3:
          optional: true
        mb:
          optional: true
      # This example config specifies three RDT classes (or resctrl groups) with L3
      # CAT configured
      resctrlGroups:
        Guaranteed:
          l3schema:
            all: "100%"
      # Specify CacheId (typically correspons CPU socket) specific setting
      #      1: "80%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 100
      #      1-3: 80
        Burstable:
          l3schema:
            all: "66%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 66
        BestEffort:
          l3schema:
            all: "33%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 33
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.node.cl0-slave1
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    topology-aware:
      PinCPU: false
      PinMemory: true
      PreferIsolatedCPUs: false
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # This is an example configuration for static-pools policy.
      # The imaginary example system here consists of 4 sockets, 4 cores, 2 threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    config:
      # Common options
      options:
        l3:
          optional: true
        mb:
          optional: true
      # This example config specifies three RDT classes (or resctrl groups) with L3
      # CAT configured
      resctrlGroups:
        Guaranteed:
          l3schema:
            all: "100%"
      # Specify CacheId (typically correspons CPU socket) specific setting
      #      1: "80%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 100
      #      1-3: 80
        Burstable:
          l3schema:
            all: "66%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 66
        BestEffort:
          l3schema:
            all: "33%"
      # MBA (Memory Bandwidth Allocation)
      #    mbschema:
      #      all: 33
  dump: |+
    Config: full:.*,short:.*Stop.*,off:.*List.*
    File: /tmp/cri-selective-debug.dump
  logger: |+
    Debug: resource-manager,cache,policy,message
