language: go

dist: bionic

go:
  - 1.12.x

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

sudo: required

before_install:
  ## checkers
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0

script:
  - make format
  - make golangci-lint
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
