apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cri-resmgr
webhooks:
- name: cri-resmgr.intel.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  clientConfig:
    service:
      namespace: cri-resmgr
      name: cri-resmgr-webhook
    caBundle: CA_BUNDLE_PLACEHOLDER
