name: Publish

on:
  push:
    branches:
        - master
        - documentation/test

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docs builder image
      run: make site-build
    - name: Branch off base for updated gh-pages
      run: |
        git branch gh-pages
        git checkout gh-pages
    - name: Add latest generated docs to gh-pages
      shell: bash
      run: |
        touch _build/html/.nojekyll
        git --work-tree _build/html add --no-all -v .
        author=$(git log --merges --pretty=format:%an -n 1)
        email=$(git log --merges --pretty=format:%ae -n 1)
        git config --global user.name "$author"
        git config --global user.email "$email"
        git commit -m "publish-docs.yml: generated latest html output."
    - name: Publish/force-push to gh-pages
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push -f https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
